### ISSUE TITLE
Change naming from show to load or get

### ISSUE THREAD

**Issue by mortengjesing** [everis-technology/Tfe.NetClient#9]
## Describe the proposal
I think naming `Show` is confusing, and would suggest to change it to `Load` or `Get` instead

### Example
[ShowAsync(string runId) -> LoadAsync(string runId) or GetAsync(string runId)](https://github.com/everis-technology/Tfe.NetClient/blob/6aed52cb943ba83b8062f8815d7c7ee6b47240d8/src/Tfe.NetClient/Features/Runs/Run.cs#L57)

**Comment by cmendible** [comment]
Changed to `GetAsync` in ebb7bf4
